import { PrismaClient } from '@prisma/client'
import { Decimal } from '../num'

const prisma = new PrismaClient()

export async function seedSignalTrades() {
  console.log('🌱 Seeding signal trades...')

  // Create portfolio settings first
  const settings = await prisma.portfolioSetting.upsert({
    where: { id: 'default-settings' },
    update: {},
    create: {
      id: 'default-settings',
      baseCapitalUsd: new Decimal('100000'),
      positionModel: 'RISK_BASED',
      feeBps: 10, // 0.1%
      slippageBps: 5, // 0.05%
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    }
  })

  // Sample trades spanning multiple months
  const trades = [
    // January 2024
    {
      symbol: 'BTC',
      direction: 'LONG' as const,
      entryTime: new Date('2024-01-02T10:30:00Z'),
      entryPrice: new Decimal('42000'),
      stopLoss: new Decimal('40000'),
      takeProfit: new Decimal('45000'),
      exitTime: new Date('2024-01-08T14:45:00Z'),
      exitPrice: new Decimal('44800'),
      conviction: 4,
      riskPct: new Decimal('2'),
      tags: '["crypto", "btc", "breakout"]',
      notes: 'Strong breakout above resistance with volume confirmation',
      status: 'CLOSED' as const,
    },
    {
      symbol: 'ETH',
      direction: 'SHORT' as const,
      entryTime: new Date('2024-01-05T09:15:00Z'),
      entryPrice: new Decimal('2650'),
      stopLoss: new Decimal('2700'),
      takeProfit: new Decimal('2500'),
      exitTime: new Date('2024-01-12T16:20:00Z'),
      exitPrice: new Decimal('2520'),
      conviction: 3,
      riskPct: new Decimal('1.8'),
      tags: '["crypto", "eth", "bearish"]',
      notes: 'Bearish divergence on daily chart with weak volume',
      status: 'CLOSED' as const,
    },
    {
      symbol: 'SOL',
      direction: 'LONG' as const,
      entryTime: new Date('2024-01-15T11:45:00Z'),
      entryPrice: new Decimal('95.40'),
      stopLoss: new Decimal('90.00'),
      takeProfit: new Decimal('105.00'),
      exitTime: new Date('2024-01-22T13:30:00Z'),
      exitPrice: new Decimal('102.80'),
      conviction: 5,
      riskPct: new Decimal('3'),
      tags: '["crypto", "sol", "alt", "support"]',
      notes: 'Major support bounce with increasing volume',
      status: 'CLOSED' as const,
    },
    {
      symbol: 'AVAX',
      direction: 'LONG' as const,
      entryTime: new Date('2024-01-18T08:30:00Z'),
      entryPrice: new Decimal('32.15'),
      stopLoss: new Decimal('30.00'),
      takeProfit: new Decimal('36.00'),
      exitTime: new Date('2024-01-25T15:45:00Z'),
      exitPrice: new Decimal('35.80'),
      conviction: 3,
      riskPct: new Decimal('2'),
      tags: '["crypto", "avax", "alt", "consolidation"]',
      notes: 'Breakout from consolidation pattern',
      status: 'CLOSED' as const,
    },
    {
      symbol: 'MATIC',
      direction: 'SHORT' as const,
      entryTime: new Date('2024-01-22T14:20:00Z'),
      entryPrice: new Decimal('0.85'),
      stopLoss: new Decimal('0.88'),
      takeProfit: new Decimal('0.75'),
      exitTime: new Date('2024-01-28T11:15:00Z'),
      exitPrice: new Decimal('0.78'),
      conviction: 2,
      riskPct: new Decimal('1.5'),
      tags: '["crypto", "matic", "alt", "resistance"]',
      notes: 'Resistance rejection with volume',
      status: 'CLOSED' as const,
    },

    // February 2024
    {
      symbol: 'BTC',
      direction: 'LONG' as const,
      entryTime: new Date('2024-02-01T09:00:00Z'),
      entryPrice: new Decimal('43000'),
      stopLoss: new Decimal('41000'),
      takeProfit: new Decimal('46000'),
      exitTime: new Date('2024-02-10T16:30:00Z'),
      exitPrice: new Decimal('45500'),
      conviction: 4,
      riskPct: new Decimal('2.5'),
      tags: '["crypto", "btc", "momentum"]',
      notes: 'Strong momentum continuation with institutional buying',
      status: 'CLOSED' as const,
    },
    {
      symbol: 'ETH',
      direction: 'LONG' as const,
      entryTime: new Date('2024-02-05T10:45:00Z'),
      entryPrice: new Decimal('2580'),
      stopLoss: new Decimal('2450'),
      takeProfit: new Decimal('2800'),
      exitTime: new Date('2024-02-15T12:20:00Z'),
      exitPrice: new Decimal('2750'),
      conviction: 4,
      riskPct: new Decimal('2.2'),
      tags: '["crypto", "eth", "defi"]',
      notes: 'DeFi narrative resurgence with TVL growth',
      status: 'CLOSED' as const,
    },
    {
      symbol: 'ADA',
      direction: 'SHORT' as const,
      entryTime: new Date('2024-02-08T13:15:00Z'),
      entryPrice: new Decimal('0.52'),
      stopLoss: new Decimal('0.55'),
      takeProfit: new Decimal('0.45'),
      exitTime: new Date('2024-02-20T09:30:00Z'),
      exitPrice: new Decimal('0.48'),
      conviction: 3,
      riskPct: new Decimal('1.8'),
      tags: '["crypto", "ada", "alt", "weakness"]',
      notes: 'Technical weakness after failed breakout',
      status: 'CLOSED' as const,
    },
    {
      symbol: 'DOT',
      direction: 'LONG' as const,
      entryTime: new Date('2024-02-12T11:00:00Z'),
      entryPrice: new Decimal('7.20'),
      stopLoss: new Decimal('6.80'),
      takeProfit: new Decimal('8.00'),
      exitTime: new Date('2024-02-25T14:45:00Z'),
      exitPrice: new Decimal('7.85'),
      conviction: 3,
      riskPct: new Decimal('2'),
      tags: '["crypto", "dot", "alt", "parachain"]',
      notes: 'Parachain auction momentum building',
      status: 'CLOSED' as const,
    },
    {
      symbol: 'LINK',
      direction: 'LONG' as const,
      entryTime: new Date('2024-02-18T08:30:00Z'),
      entryPrice: new Decimal('14.50'),
      stopLoss: new Decimal('13.50'),
      takeProfit: new Decimal('16.00'),
      exitTime: new Date('2024-02-28T16:20:00Z'),
      exitPrice: new Decimal('15.80'),
      conviction: 4,
      riskPct: new Decimal('2.3'),
      tags: '["crypto", "link", "oracle", "defi"]',
      notes: 'Oracle demand surge with DeFi expansion',
      status: 'CLOSED' as const,
    },

    // March 2024
    {
      symbol: 'BTC',
      direction: 'SHORT' as const,
      entryTime: new Date('2024-03-01T12:00:00Z'),
      entryPrice: new Decimal('45000'),
      stopLoss: new Decimal('46000'),
      takeProfit: new Decimal('42000'),
      exitTime: new Date('2024-03-08T10:15:00Z'),
      exitPrice: new Decimal('43200'),
      conviction: 3,
      riskPct: new Decimal('2'),
      tags: '["crypto", "btc", "correction"]',
      notes: 'Expected correction after strong rally',
      status: 'CLOSED' as const,
    },
    {
      symbol: 'ETH',
      direction: 'LONG' as const,
      entryTime: new Date('2024-03-05T09:30:00Z'),
      entryPrice: new Decimal('2700'),
      stopLoss: new Decimal('2600'),
      takeProfit: new Decimal('2900'),
      exitTime: new Date('2024-03-15T15:45:00Z'),
      exitPrice: new Decimal('2850'),
      conviction: 4,
      riskPct: new Decimal('2.5'),
      tags: '["crypto", "eth", "upgrade"]',
      notes: 'Ethereum upgrade anticipation building',
      status: 'CLOSED' as const,
    },
    {
      symbol: 'UNI',
      direction: 'LONG' as const,
      entryTime: new Date('2024-03-10T11:20:00Z'),
      entryPrice: new Decimal('8.50'),
      stopLoss: new Decimal('8.00'),
      takeProfit: new Decimal('9.50'),
      exitTime: new Date('2024-03-20T13:30:00Z'),
      exitPrice: new Decimal('9.20'),
      conviction: 3,
      riskPct: new Decimal('2'),
      tags: '["crypto", "uni", "defi", "dex"]',
      notes: 'DEX volume surge with market recovery',
      status: 'CLOSED' as const,
    },
    {
      symbol: 'ATOM',
      direction: 'SHORT' as const,
      entryTime: new Date('2024-03-12T14:45:00Z'),
      entryPrice: new Decimal('12.80'),
      stopLoss: new Decimal('13.50'),
      takeProfit: new Decimal('11.50'),
      exitTime: new Date('2024-03-22T09:15:00Z'),
      exitPrice: new Decimal('12.20'),
      conviction: 2,
      riskPct: new Decimal('1.5'),
      tags: '["crypto", "atom", "cosmos", "weakness"]',
      notes: 'Cosmos ecosystem weakness showing',
      status: 'CLOSED' as const,
    },
    {
      symbol: 'NEAR',
      direction: 'LONG' as const,
      entryTime: new Date('2024-03-18T10:00:00Z'),
      entryPrice: new Decimal('3.20'),
      stopLoss: new Decimal('3.00'),
      takeProfit: new Decimal('3.60'),
      exitTime: new Date('2024-03-28T16:30:00Z'),
      exitPrice: new Decimal('3.45'),
      conviction: 3,
      riskPct: new Decimal('2.2'),
      tags: '["crypto", "near", "alt", "layer1"]',
      notes: 'Layer 1 narrative gaining traction',
      status: 'CLOSED' as const,
    },

    // April 2024
    {
      symbol: 'BTC',
      direction: 'LONG' as const,
      entryTime: new Date('2024-04-01T08:30:00Z'),
      entryPrice: new Decimal('44000'),
      stopLoss: new Decimal('42000'),
      takeProfit: new Decimal('48000'),
      exitTime: new Date('2024-04-12T14:20:00Z'),
      exitPrice: new Decimal('47200'),
      conviction: 5,
      riskPct: new Decimal('3'),
      tags: '["crypto", "btc", "halving"]',
      notes: 'Bitcoin halving anticipation driving demand',
      status: 'CLOSED' as const,
    },
    {
      symbol: 'ETH',
      direction: 'LONG' as const,
      entryTime: new Date('2024-04-05T09:45:00Z'),
      entryPrice: new Decimal('2800'),
      stopLoss: new Decimal('2700'),
      takeProfit: new Decimal('3100'),
      exitTime: new Date('2024-04-18T11:30:00Z'),
      exitPrice: new Decimal('3050'),
      conviction: 4,
      riskPct: new Decimal('2.8'),
      tags: '["crypto", "eth", "upgrade", "staking"]',
      notes: 'Ethereum staking rewards driving demand',
      status: 'CLOSED' as const,
    },
    {
      symbol: 'SOL',
      direction: 'LONG' as const,
      entryTime: new Date('2024-04-08T12:15:00Z'),
      entryPrice: new Decimal('105.00'),
      stopLoss: new Decimal('100.00'),
      takeProfit: new Decimal('115.00'),
      exitTime: new Date('2024-04-20T15:45:00Z'),
      exitPrice: new Decimal('112.50'),
      conviction: 4,
      riskPct: new Decimal('2.5'),
      tags: '["crypto", "sol", "alt", "ecosystem"]',
      notes: 'Solana ecosystem growth accelerating',
      status: 'CLOSED' as const,
    },
    {
      symbol: 'AVAX',
      direction: 'SHORT' as const,
      entryTime: new Date('2024-04-12T13:30:00Z'),
      entryPrice: new Decimal('38.50'),
      stopLoss: new Decimal('40.00'),
      takeProfit: new Decimal('35.00'),
      exitTime: new Date('2024-04-25T10:20:00Z'),
      exitPrice: new Decimal('36.80'),
      conviction: 3,
      riskPct: new Decimal('2'),
      tags: '["crypto", "avax", "alt", "correction"]',
      notes: 'Expected correction after strong rally',
      status: 'CLOSED' as const,
    },
    {
      symbol: 'MATIC',
      direction: 'LONG' as const,
      entryTime: new Date('2024-04-15T10:00:00Z'),
      entryPrice: new Decimal('0.82'),
      stopLoss: new Decimal('0.78'),
      takeProfit: new Decimal('0.90'),
      exitTime: new Date('2024-04-28T14:15:00Z'),
      exitPrice: new Decimal('0.88'),
      conviction: 3,
      riskPct: new Decimal('2.2'),
      tags: '["crypto", "matic", "alt", "layer2"]',
      notes: 'Layer 2 scaling narrative strong',
      status: 'CLOSED' as const,
    },

    // May 2024 (some open positions)
    {
      symbol: 'BTC',
      direction: 'LONG' as const,
      entryTime: new Date('2024-05-01T09:30:00Z'),
      entryPrice: new Decimal('48000'),
      stopLoss: new Decimal('46000'),
      takeProfit: new Decimal('52000'),
      conviction: 4,
      riskPct: new Decimal('2.5'),
      tags: '["crypto", "btc", "momentum"]',
      notes: 'Post-halving momentum continuation',
      status: 'OPEN' as const,
    },
    {
      symbol: 'ETH',
      direction: 'LONG' as const,
      entryTime: new Date('2024-05-03T11:15:00Z'),
      entryPrice: new Decimal('3100'),
      stopLoss: new Decimal('3000'),
      takeProfit: new Decimal('3400'),
      conviction: 4,
      riskPct: new Decimal('2.8'),
      tags: '["crypto", "eth", "upgrade"]',
      notes: 'Ethereum upgrade implementation ongoing',
      status: 'OPEN' as const,
    },
    {
      symbol: 'SOL',
      direction: 'SHORT' as const,
      entryTime: new Date('2024-05-05T14:20:00Z'),
      entryPrice: new Decimal('115.00'),
      stopLoss: new Decimal('120.00'),
      takeProfit: new Decimal('105.00'),
      conviction: 3,
      riskPct: new Decimal('2'),
      tags: '["crypto", "sol", "alt", "overbought"]',
      notes: 'Technical overbought conditions',
      status: 'OPEN' as const,
    },
    {
      symbol: 'AVAX',
      direction: 'LONG' as const,
      entryTime: new Date('2024-05-08T08:45:00Z'),
      entryPrice: new Decimal('35.20'),
      stopLoss: new Decimal('33.00'),
      takeProfit: new Decimal('40.00'),
      conviction: 3,
      riskPct: new Decimal('2.2'),
      tags: '["crypto", "avax", "alt", "recovery"]',
      notes: 'Avalanche ecosystem recovery signs',
      status: 'OPEN' as const,
    },
    {
      symbol: 'LINK',
      direction: 'LONG' as const,
      entryTime: new Date('2024-05-10T12:30:00Z'),
      entryPrice: new Decimal('16.50'),
      stopLoss: new Decimal('15.50'),
      takeProfit: new Decimal('18.50'),
      conviction: 4,
      riskPct: new Decimal('2.5'),
      tags: '["crypto", "link", "oracle", "ai"]',
      notes: 'AI narrative driving oracle demand',
      status: 'OPEN' as const,
    },
  ]

  // Create trades
  for (const trade of trades) {
    const slug = `${trade.symbol.toLowerCase()}-${trade.direction.toLowerCase()}-${trade.entryTime.getTime()}`
    await prisma.signalTrade.upsert({
      where: {
        slug: slug
      },
      update: {},
      create: {
        ...trade,
        slug: slug,
        createdAt: trade.entryTime,
        updatedAt: trade.exitTime || trade.entryTime,
      }
    })
  }

  console.log(`✅ Created ${trades.length} signal trades`)
  return trades
}
